brew "awscli"
brew "direnv"
brew "exiftool"
brew "fnm"
brew "gh"
brew "starship"
brew "zellij"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

cask "font-jetbrains-mono-nerd-font"
cask "ghostty"
cask "ngrok"
