add_newline = false
command_timeout = 1000

[nodejs]
format = "via [ $version](bold green) "

[git_branch]
format = "on [$branch](bold purple) "

[git_status]
format = "([$all_status$ahead_behind](bold red)) "

[directory]
truncation_length = 3

[aws]
format = 'on [$symbol($profile )(\($region\))]($style) '
style = "bold yellow"

[aws.profile_aliases]
default = ""
